[package]
name = "shields-up-engineering"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rocket = "0.5.1"
ws = { package = "rocket_ws", version = "0.1.1" }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
